name: Build and Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Create CRA production env
        run: |
          mkdir -p my-react-app
          echo "REACT_APP_FILEBASE_RPC_TOKEN=${{ secrets.FILEBASE_RPC_TOKEN }}" >> my-react-app/.env.production.local
          echo "REACT_APP_ALCHEMY_API_KEY=${{ secrets.REACT_APP_ALCHEMY_API_KEY }}" >> my-react-app/.env.production.local
          echo "REACT_APP_CHAIN_ID=${{ secrets.REACT_APP_CHAIN_ID }}" >> my-react-app/.env.production.local
          echo "REACT_APP_NETWORK_NAME=${{ secrets.REACT_APP_NETWORK_NAME }}" >> my-react-app/.env.production.local
          echo "REACT_APP_COLLECTION_ADDRESS=${{ secrets.REACT_APP_COLLECTION_ADDRESS }}" >> my-react-app/.env.production.local
          echo "REACT_APP_MARKETPLACE_ADDRESS=${{ secrets.REACT_APP_MARKETPLACE_ADDRESS }}" >> my-react-app/.env.production.local
          echo "REACT_APP_BLOCK_EXPLORER=${{ secrets.REACT_APP_BLOCK_EXPLORER }}" >> my-react-app/.env.production.local
          echo "REACT_APP_IPFS_PRIMARY_GATEWAY=${{ secrets.REACT_APP_IPFS_PRIMARY_GATEWAY }}" >> my-react-app/.env.production.local
          # Optional Firebase config via secrets (or rely on committed my-react-app/.env.production)
          # echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> my-react-app/.env.production.local
          # echo "REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> my-react-app/.env.production.local
          # echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}" >> my-react-app/.env.production.local
          # echo "REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}" >> my-react-app/.env.production.local
          # echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}" >> my-react-app/.env.production.local
          # echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}" >> my-react-app/.env.production.local

      - name: Install and build
        working-directory: my-react-app
        run: |
          npm ci
          npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          entryPoint: ./
